package msggen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

const conductorImport = "conductor.dev/conductor"

// timeMapped maps builtin_interfaces types onto Go time types instead of
// generating structs for them; the cdr codec serializes them natively.
var timeMapped = map[string]string{
	"builtin_interfaces/msg/Time":     "time.Time",
	"builtin_interfaces/msg/Duration": "time.Duration",
}

var builtinGoTypes = map[string]string{
	"bool": "bool", "byte": "uint8",
	"int8": "int8", "uint8": "uint8", "int16": "int16", "uint16": "uint16",
	"int32": "int32", "uint32": "uint32", "int64": "int64", "uint64": "uint64",
	"float32": "float32", "float64": "float64", "string": "string",
}

// Generate emits one Go source file (package goPkg) containing structs,
// constants, //ros:type directives, and hash registrations for the target
// types and everything they transitively reference. Service targets
// (pkg/srv/Name) produce Request/Response structs plus a RegisterService
// call; the synthesized _Event message participates in hashing only.
func Generate(r *Resolver, targets []string, goPkg string) ([]byte, error) {
	// Collect the full generation set, excluding time-mapped types.
	set := map[string]*Message{}
	var visit func(name string) error
	visit = func(name string) error {
		if _, done := set[name]; done || timeMapped[name] != "" {
			return nil
		}
		m, err := r.Resolve(name)
		if err != nil {
			return err
		}
		set[name] = m
		for _, f := range m.Fields {
			if f.Type.Nested != "" {
				if err := visit(f.Type.Nested); err != nil {
					return err
				}
			}
		}
		return nil
	}
	var services []*Service
	var actions []*ActionDef
	for _, t := range targets {
		switch {
		case IsServiceName(t):
			svc, err := r.ResolveService(t)
			if err != nil {
				return nil, err
			}
			services = append(services, svc)
			if err := visit(svc.Request.FullName()); err != nil {
				return nil, err
			}
			if err := visit(svc.Response.FullName()); err != nil {
				return nil, err
			}
		case IsActionName(t):
			a, err := r.ResolveAction(t)
			if err != nil {
				return nil, err
			}
			actions = append(actions, a)
			for _, m := range []*Message{a.Goal, a.Result, a.Feedback} {
				if err := visit(m.FullName()); err != nil {
					return nil, err
				}
			}
		default:
			if err := visit(t); err != nil {
				return nil, err
			}
		}
	}
	sort.Slice(services, func(i, j int) bool { return services[i].FullName() < services[j].FullName() })
	sort.Slice(actions, func(i, j int) bool { return actions[i].FullName() < actions[j].FullName() })

	names := make([]string, 0, len(set))
	bare := map[string]string{}
	needTime := false
	for name, m := range set {
		names = append(names, name)
		if prev, clash := bare[goName(m.Name)]; clash {
			return nil, fmt.Errorf("Go type name collision: %s and %s would both be %q in package %s; generate them separately",
				prev, name, goName(m.Name), goPkg)
		}
		bare[goName(m.Name)] = name
		for _, f := range m.Fields {
			if timeMapped[f.Type.Nested] != "" {
				needTime = true
			}
		}
	}
	sort.Strings(names)

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by conductor msggen from %s. DO NOT EDIT.\n\n", strings.Join(targets, ", "))
	fmt.Fprintf(&b, "package %s\n\n", goPkg)
	b.WriteString("import (\n")
	if needTime {
		b.WriteString("\t\"time\"\n\n")
	}
	fmt.Fprintf(&b, "\tconductor %q\n)\n", conductorImport)

	for _, name := range names {
		m := set[name]
		writeConstants(&b, m)
		fmt.Fprintf(&b, "\n//ros:type %s\ntype %s struct {\n", name, goName(m.Name))
		for _, f := range m.Fields {
			goType, err := goFieldType(f.Type)
			if err != nil {
				return nil, fmt.Errorf("%s field %s: %w", name, f.Name, err)
			}
			fmt.Fprintf(&b, "\t%s %s\n", exportName(f.Name), goType)
		}
		b.WriteString("}\n")
	}

	b.WriteString("\nfunc init() {\n")
	for _, name := range names {
		td, err := r.Describe(name)
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&b, "\tconductor.RegisterMessage[%s](%q,\n\t\t%q)\n", goName(set[name].Name), name, td.Hash())
	}
	for _, svc := range services {
		td, err := r.Describe(svc.FullName())
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&b, "\tconductor.RegisterService[%s, %s](%q,\n\t\t%q)\n",
			goName(svc.Request.Name), goName(svc.Response.Name), svc.FullName(), td.Hash())
	}
	for _, a := range actions {
		hashes := map[string]string{}
		for _, derived := range []string{a.SendGoal.FullName(), a.GetResult.FullName(), a.FeedbackMessage.FullName()} {
			td, err := r.Describe(derived)
			if err != nil {
				return nil, err
			}
			hashes[derived] = td.Hash()
		}
		fmt.Fprintf(&b, "\tconductor.RegisterAction[%s, %s, %s](conductor.ActionInfo{\n",
			goName(a.Goal.Name), goName(a.Feedback.Name), goName(a.Result.Name))
		fmt.Fprintf(&b, "\t\tName:            %q,\n", a.FullName())
		fmt.Fprintf(&b, "\t\tSendGoal:        conductor.MessageInfo{Name: %q, Hash: %q},\n", a.SendGoal.FullName(), hashes[a.SendGoal.FullName()])
		fmt.Fprintf(&b, "\t\tGetResult:       conductor.MessageInfo{Name: %q, Hash: %q},\n", a.GetResult.FullName(), hashes[a.GetResult.FullName()])
		fmt.Fprintf(&b, "\t\tFeedbackMessage: conductor.MessageInfo{Name: %q, Hash: %q},\n", a.FeedbackMessage.FullName(), hashes[a.FeedbackMessage.FullName()])
		b.WriteString("\t})\n")
	}
	b.WriteString("}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting generated code: %w (bug in msggen)", err)
	}
	return src, nil
}

func writeConstants(b *bytes.Buffer, m *Message) {
	if len(m.Constants) == 0 {
		return
	}
	b.WriteString("\nconst (\n")
	for _, c := range m.Constants {
		// Constant names keep their ROS form (Type_NAME) so the mapping to
		// the .msg definition stays mechanical.
		fmt.Fprintf(b, "\t%s_%s = %s\n", m.Name, c.Name, constValue(c))
	}
	b.WriteString(")\n")
}

func constValue(c Constant) string {
	if c.Type != "string" {
		return c.Value
	}
	v := c.Value
	if len(v) >= 2 && (v[0] == '"' || v[0] == '\'') && v[len(v)-1] == v[0] {
		v = v[1 : len(v)-1]
	}
	return strconv.Quote(v)
}

func goFieldType(ft FieldType) (string, error) {
	var elem string
	switch {
	case ft.Nested != "":
		if mapped := timeMapped[ft.Nested]; mapped != "" {
			elem = mapped
		} else {
			parts := strings.Split(ft.Nested, "/")
			elem = parts[len(parts)-1]
		}
	default:
		elem = builtinGoTypes[ft.Builtin]
		if elem == "" {
			return "", fmt.Errorf("unsupported builtin %q", ft.Builtin)
		}
	}
	switch ft.Kind {
	case Scalar:
		return elem, nil
	case Array:
		return fmt.Sprintf("[%d]%s", ft.Capacity, elem), nil
	default: // bounded and unbounded sequences are Go slices
		return "[]" + elem, nil
	}
}

// goName converts a ROS type name to its Go type name; the only transform is
// dropping underscores from service sub-message names (SetBool_Request ->
// SetBoolRequest).
func goName(rosName string) string {
	return strings.ReplaceAll(rosName, "_", "")
}

// exportName converts a ROS snake_case field name to an exported Go name.
func exportName(s string) string {
	var b strings.Builder
	for _, part := range strings.Split(s, "_") {
		if part == "" {
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]))
		b.WriteString(part[1:])
	}
	return b.String()
}
