// Code generated by conductor msggen from std_srvs/srv/SetBool, std_srvs/srv/Trigger. DO NOT EDIT.

package srvs

import (
	conductor "conductor.dev/conductor"
)

//ros:type std_srvs/srv/SetBool_Request
type SetBoolRequest struct {
	Data bool
}

//ros:type std_srvs/srv/SetBool_Response
type SetBoolResponse struct {
	Success bool
	Message string
}

//ros:type std_srvs/srv/Trigger_Request
type TriggerRequest struct {
	StructureNeedsAtLeastOneMember uint8
}

//ros:type std_srvs/srv/Trigger_Response
type TriggerResponse struct {
	Success bool
	Message string
}

func init() {
	conductor.RegisterMessage[SetBoolRequest]("std_srvs/srv/SetBool_Request",
		"RIHS01_c62fbb99d94e1b25e8ef9e109f9581956bb1b3361a45a4e5810c36a90d29932e")
	conductor.RegisterMessage[SetBoolResponse]("std_srvs/srv/SetBool_Response",
		"RIHS01_d0814e7f7b4880ab77e9c57426c7aa1562ab69f11eef8e2e968812f9cbd0b059")
	conductor.RegisterMessage[TriggerRequest]("std_srvs/srv/Trigger_Request",
		"RIHS01_d010825374ce8918e72bfd826c82603e60f45419e932ea976f807b74a863a199")
	conductor.RegisterMessage[TriggerResponse]("std_srvs/srv/Trigger_Response",
		"RIHS01_2d946c21e2fc3f1e9ca6986a8191d85fcc70097a8bb7771a053564bc47009cdf")
	conductor.RegisterService[SetBoolRequest, SetBoolResponse]("std_srvs/srv/SetBool",
		"RIHS01_abe9e4bb6b41b40e6789712c00ec8871923e089af3f667a79992a428cff2da0a")
	conductor.RegisterService[TriggerRequest, TriggerResponse]("std_srvs/srv/Trigger",
		"RIHS01_eeff2cd6fa5ad9d27cdf4dec64818317839b62f212a91e6b5304b634b2062c5f")
}
