// Code generated by conductor msggen from geometry_msgs/msg/Twist, turtlesim_msgs/msg/Pose, turtlesim_msgs/srv/Spawn, turtlesim_msgs/srv/SetPen, turtlesim_msgs/srv/TeleportAbsolute, turtlesim_msgs/action/RotateAbsolute. DO NOT EDIT.

package main

import (
	conductor "conductor.dev/conductor"
)

//ros:type geometry_msgs/msg/Twist
type Twist struct {
	Linear  Vector3
	Angular Vector3
}

//ros:type geometry_msgs/msg/Vector3
type Vector3 struct {
	X float64
	Y float64
	Z float64
}

//ros:type turtlesim_msgs/action/RotateAbsolute_Feedback
type RotateAbsoluteFeedback struct {
	Remaining float32
}

//ros:type turtlesim_msgs/action/RotateAbsolute_Goal
type RotateAbsoluteGoal struct {
	Theta float32
}

//ros:type turtlesim_msgs/action/RotateAbsolute_Result
type RotateAbsoluteResult struct {
	Delta float32
}

//ros:type turtlesim_msgs/msg/Pose
type Pose struct {
	X               float32
	Y               float32
	Theta           float32
	LinearVelocity  float32
	AngularVelocity float32
}

//ros:type turtlesim_msgs/srv/SetPen_Request
type SetPenRequest struct {
	R     uint8
	G     uint8
	B     uint8
	Width uint8
	Off   uint8
}

//ros:type turtlesim_msgs/srv/SetPen_Response
type SetPenResponse struct {
	StructureNeedsAtLeastOneMember uint8
}

//ros:type turtlesim_msgs/srv/Spawn_Request
type SpawnRequest struct {
	X     float32
	Y     float32
	Theta float32
	Name  string
}

//ros:type turtlesim_msgs/srv/Spawn_Response
type SpawnResponse struct {
	Name string
}

//ros:type turtlesim_msgs/srv/TeleportAbsolute_Request
type TeleportAbsoluteRequest struct {
	X     float32
	Y     float32
	Theta float32
}

//ros:type turtlesim_msgs/srv/TeleportAbsolute_Response
type TeleportAbsoluteResponse struct {
	StructureNeedsAtLeastOneMember uint8
}

func init() {
	conductor.RegisterMessage[Twist]("geometry_msgs/msg/Twist",
		"RIHS01_9c45bf16fe0983d80e3cfe750d6835843d265a9a6c46bd2e609fcddde6fb8d2a")
	conductor.RegisterMessage[Vector3]("geometry_msgs/msg/Vector3",
		"RIHS01_cc12fe83e4c02719f1ce8070bfd14aecd40f75a96696a67a2a1f37f7dbb0765d")
	conductor.RegisterMessage[RotateAbsoluteFeedback]("turtlesim_msgs/action/RotateAbsolute_Feedback",
		"RIHS01_723543631aa0eb39a542d5d1a99972b4111db0640add8466ba6673f4f52289d8")
	conductor.RegisterMessage[RotateAbsoluteGoal]("turtlesim_msgs/action/RotateAbsolute_Goal",
		"RIHS01_fd5e33ea83e08981c70c771972b70bd9b8fc70c6dcc4220f7af9bedde3322208")
	conductor.RegisterMessage[RotateAbsoluteResult]("turtlesim_msgs/action/RotateAbsolute_Result",
		"RIHS01_5ed906c975a8755df7f9bfb5677839187d8deccfe8d24ef322aeafbe5d31aab2")
	conductor.RegisterMessage[Pose]("turtlesim_msgs/msg/Pose",
		"RIHS01_37b07ace09a0ed2c5b774b1410dec972dfd1d292de5656ebc2b075ac646e09c8")
	conductor.RegisterMessage[SetPenRequest]("turtlesim_msgs/srv/SetPen_Request",
		"RIHS01_f5b69a5de97b15ce692d3e7d248022516be9b951db82cec8066b92c5b9f04019")
	conductor.RegisterMessage[SetPenResponse]("turtlesim_msgs/srv/SetPen_Response",
		"RIHS01_4f5632338b4e216c05a34026de6275e9191c4d549dcb3015fb25648ee20796de")
	conductor.RegisterMessage[SpawnRequest]("turtlesim_msgs/srv/Spawn_Request",
		"RIHS01_f1c85cfdae55164190e25034ec31f830936de5e7e6c0b20d1ebbfee2deeb2b39")
	conductor.RegisterMessage[SpawnResponse]("turtlesim_msgs/srv/Spawn_Response",
		"RIHS01_add40fd4f4892878498f6fe01af629b171fbf2b76fcc4f473e8f9b65be3735bb")
	conductor.RegisterMessage[TeleportAbsoluteRequest]("turtlesim_msgs/srv/TeleportAbsolute_Request",
		"RIHS01_342b1b8f43a73130bf1d148c0d4543fb7e8ae1fc79dabed02e7acfe4c6da376d")
	conductor.RegisterMessage[TeleportAbsoluteResponse]("turtlesim_msgs/srv/TeleportAbsolute_Response",
		"RIHS01_4833b6c087856ff19a17dac8790ebe8a0837594d798a4d54d132c9a6b01b2a67")
	conductor.RegisterService[SetPenRequest, SetPenResponse]("turtlesim_msgs/srv/SetPen",
		"RIHS01_9d5465611d8822f9ded80bfff0f697bb1046c2e2ca428502c38cb2bfff241325")
	conductor.RegisterService[SpawnRequest, SpawnResponse]("turtlesim_msgs/srv/Spawn",
		"RIHS01_1538b7b668cce0074f0ca9fa992bdeb6979bda1f722fc7ea33ca47b408aa32e9")
	conductor.RegisterService[TeleportAbsoluteRequest, TeleportAbsoluteResponse]("turtlesim_msgs/srv/TeleportAbsolute",
		"RIHS01_bd9ecb11b762865429dff079c4c296c97b751c4ec968f8d1893292c86d3d1b7c")
	conductor.RegisterAction[RotateAbsoluteGoal, RotateAbsoluteFeedback, RotateAbsoluteResult](conductor.ActionInfo{
		Name:            "turtlesim_msgs/action/RotateAbsolute",
		SendGoal:        conductor.MessageInfo{Name: "turtlesim_msgs/action/RotateAbsolute_SendGoal", Hash: "RIHS01_3d5d3cfcbb721f88038eaedcd4af95565360a82b36f1983e3a6c7448d2d18fbe"},
		GetResult:       conductor.MessageInfo{Name: "turtlesim_msgs/action/RotateAbsolute_GetResult", Hash: "RIHS01_f96fd02477be2a47122fca142e960d407b24850c6eac72047872ba764473c4ef"},
		FeedbackMessage: conductor.MessageInfo{Name: "turtlesim_msgs/action/RotateAbsolute_FeedbackMessage", Hash: "RIHS01_bef10993e1ee82b35f99f7e390bac1e6cc64e2a3090536887832e122aa71f1b5"},
	})
}
