// Code generated by conductor msggen from nav2_msgs/srv/ManageLifecycleNodes, nav2_msgs/action/BackUp, nav2_msgs/action/NavigateToPose, nav2_msgs/action/Spin, geometry_msgs/msg/PoseWithCovarianceStamped, geometry_msgs/msg/TwistStamped, sensor_msgs/msg/BatteryState. DO NOT EDIT.

package main

import (
	"time"

	conductor "conductor.dev/conductor"
)

//ros:type geometry_msgs/msg/Point
type Point struct {
	X float64
	Y float64
	Z float64
}

//ros:type geometry_msgs/msg/Pose
type Pose struct {
	Position    Point
	Orientation Quaternion
}

//ros:type geometry_msgs/msg/PoseStamped
type PoseStamped struct {
	Header Header
	Pose   Pose
}

//ros:type geometry_msgs/msg/PoseWithCovariance
type PoseWithCovariance struct {
	Pose       Pose
	Covariance [36]float64
}

//ros:type geometry_msgs/msg/PoseWithCovarianceStamped
type PoseWithCovarianceStamped struct {
	Header Header
	Pose   PoseWithCovariance
}

//ros:type geometry_msgs/msg/Quaternion
type Quaternion struct {
	X float64
	Y float64
	Z float64
	W float64
}

//ros:type geometry_msgs/msg/Twist
type Twist struct {
	Linear  Vector3
	Angular Vector3
}

//ros:type geometry_msgs/msg/TwistStamped
type TwistStamped struct {
	Header Header
	Twist  Twist
}

//ros:type geometry_msgs/msg/Vector3
type Vector3 struct {
	X float64
	Y float64
	Z float64
}

//ros:type nav2_msgs/action/BackUp_Feedback
type BackUpFeedback struct {
	DistanceTraveled float32
}

//ros:type nav2_msgs/action/BackUp_Goal
type BackUpGoal struct {
	Target                 Point
	Speed                  float32
	TimeAllowance          time.Duration
	DisableCollisionChecks bool
}

const (
	BackUp_Result_NONE            = 0
	BackUp_Result_UNKNOWN         = 710
	BackUp_Result_TIMEOUT         = 711
	BackUp_Result_TF_ERROR        = 712
	BackUp_Result_INVALID_INPUT   = 713
	BackUp_Result_COLLISION_AHEAD = 714
)

//ros:type nav2_msgs/action/BackUp_Result
type BackUpResult struct {
	TotalElapsedTime time.Duration
	ErrorCode        uint16
	ErrorMsg         string
}

//ros:type nav2_msgs/action/NavigateToPose_Feedback
type NavigateToPoseFeedback struct {
	CurrentPose            PoseStamped
	NavigationTime         time.Duration
	EstimatedTimeRemaining time.Duration
	NumberOfRecoveries     int16
	DistanceRemaining      float32
	PositionTrackingError  float32
	HeadingTrackingError   float32
}

//ros:type nav2_msgs/action/NavigateToPose_Goal
type NavigateToPoseGoal struct {
	Pose         PoseStamped
	BehaviorTree string
}

const (
	NavigateToPose_Result_NONE                         = 0
	NavigateToPose_Result_UNKNOWN                      = 9000
	NavigateToPose_Result_FAILED_TO_LOAD_BEHAVIOR_TREE = 9001
	NavigateToPose_Result_TF_ERROR                     = 9002
	NavigateToPose_Result_TIMEOUT                      = 9003
)

//ros:type nav2_msgs/action/NavigateToPose_Result
type NavigateToPoseResult struct {
	ErrorCode uint16
	ErrorMsg  string
}

//ros:type nav2_msgs/action/Spin_Feedback
type SpinFeedback struct {
	AngularDistanceTraveled float32
}

//ros:type nav2_msgs/action/Spin_Goal
type SpinGoal struct {
	TargetYaw              float32
	TimeAllowance          time.Duration
	DisableCollisionChecks bool
}

const (
	Spin_Result_NONE            = 0
	Spin_Result_UNKNOWN         = 700
	Spin_Result_TIMEOUT         = 701
	Spin_Result_TF_ERROR        = 702
	Spin_Result_COLLISION_AHEAD = 703
)

//ros:type nav2_msgs/action/Spin_Result
type SpinResult struct {
	TotalElapsedTime time.Duration
	ErrorCode        uint16
	ErrorMsg         string
}

const (
	ManageLifecycleNodes_Request_STARTUP   = 0
	ManageLifecycleNodes_Request_PAUSE     = 1
	ManageLifecycleNodes_Request_RESUME    = 2
	ManageLifecycleNodes_Request_RESET     = 3
	ManageLifecycleNodes_Request_SHUTDOWN  = 4
	ManageLifecycleNodes_Request_CONFIGURE = 5
	ManageLifecycleNodes_Request_CLEANUP   = 6
)

//ros:type nav2_msgs/srv/ManageLifecycleNodes_Request
type ManageLifecycleNodesRequest struct {
	Command uint8
}

//ros:type nav2_msgs/srv/ManageLifecycleNodes_Response
type ManageLifecycleNodesResponse struct {
	Success bool
}

const (
	BatteryState_POWER_SUPPLY_STATUS_UNKNOWN               = 0
	BatteryState_POWER_SUPPLY_STATUS_CHARGING              = 1
	BatteryState_POWER_SUPPLY_STATUS_DISCHARGING           = 2
	BatteryState_POWER_SUPPLY_STATUS_NOT_CHARGING          = 3
	BatteryState_POWER_SUPPLY_STATUS_FULL                  = 4
	BatteryState_POWER_SUPPLY_HEALTH_UNKNOWN               = 0
	BatteryState_POWER_SUPPLY_HEALTH_GOOD                  = 1
	BatteryState_POWER_SUPPLY_HEALTH_OVERHEAT              = 2
	BatteryState_POWER_SUPPLY_HEALTH_DEAD                  = 3
	BatteryState_POWER_SUPPLY_HEALTH_OVERVOLTAGE           = 4
	BatteryState_POWER_SUPPLY_HEALTH_UNSPEC_FAILURE        = 5
	BatteryState_POWER_SUPPLY_HEALTH_COLD                  = 6
	BatteryState_POWER_SUPPLY_HEALTH_WATCHDOG_TIMER_EXPIRE = 7
	BatteryState_POWER_SUPPLY_HEALTH_SAFETY_TIMER_EXPIRE   = 8
	BatteryState_POWER_SUPPLY_TECHNOLOGY_UNKNOWN           = 0
	BatteryState_POWER_SUPPLY_TECHNOLOGY_NIMH              = 1
	BatteryState_POWER_SUPPLY_TECHNOLOGY_LION              = 2
	BatteryState_POWER_SUPPLY_TECHNOLOGY_LIPO              = 3
	BatteryState_POWER_SUPPLY_TECHNOLOGY_LIFE              = 4
	BatteryState_POWER_SUPPLY_TECHNOLOGY_NICD              = 5
	BatteryState_POWER_SUPPLY_TECHNOLOGY_LIMN              = 6
	BatteryState_POWER_SUPPLY_TECHNOLOGY_TERNARY           = 7
	BatteryState_POWER_SUPPLY_TECHNOLOGY_VRLA              = 8
)

//ros:type sensor_msgs/msg/BatteryState
type BatteryState struct {
	Header                Header
	Voltage               float32
	Temperature           float32
	Current               float32
	Charge                float32
	Capacity              float32
	DesignCapacity        float32
	Percentage            float32
	PowerSupplyStatus     uint8
	PowerSupplyHealth     uint8
	PowerSupplyTechnology uint8
	Present               bool
	CellVoltage           []float32
	CellTemperature       []float32
	Location              string
	SerialNumber          string
}

//ros:type std_msgs/msg/Header
type Header struct {
	Stamp   time.Time
	FrameId string
}

func init() {
	conductor.RegisterMessage[Point]("geometry_msgs/msg/Point",
		"RIHS01_6963084842a9b04494d6b2941d11444708d892da2f4b09843b9c43f42a7f6881")
	conductor.RegisterMessage[Pose]("geometry_msgs/msg/Pose",
		"RIHS01_d501954e9476cea2996984e812054b68026ae0bfae789d9a10b23daf35cc90fa")
	conductor.RegisterMessage[PoseStamped]("geometry_msgs/msg/PoseStamped",
		"RIHS01_10f3786d7d40fd2b54367835614bff85d4ad3b5dab62bf8bca0cc232d73b4cd8")
	conductor.RegisterMessage[PoseWithCovariance]("geometry_msgs/msg/PoseWithCovariance",
		"RIHS01_9a7c0fd234b7f45c6098745ecccd773ca1085670e64107135397aee31c02e1bb")
	conductor.RegisterMessage[PoseWithCovarianceStamped]("geometry_msgs/msg/PoseWithCovarianceStamped",
		"RIHS01_26432f9803e43727d3c8f668d1fdb3c630f548af631e2f4e31382371bfea3b6e")
	conductor.RegisterMessage[Quaternion]("geometry_msgs/msg/Quaternion",
		"RIHS01_8a765f66778c8ff7c8ab94afcc590a2ed5325a1d9a076ffff38fbce36f458684")
	conductor.RegisterMessage[Twist]("geometry_msgs/msg/Twist",
		"RIHS01_9c45bf16fe0983d80e3cfe750d6835843d265a9a6c46bd2e609fcddde6fb8d2a")
	conductor.RegisterMessage[TwistStamped]("geometry_msgs/msg/TwistStamped",
		"RIHS01_5f0fcd4f81d5d06ad9b4c4c63e3ea51b82d6ae4d0558f1d475229b1121db6f64")
	conductor.RegisterMessage[Vector3]("geometry_msgs/msg/Vector3",
		"RIHS01_cc12fe83e4c02719f1ce8070bfd14aecd40f75a96696a67a2a1f37f7dbb0765d")
	conductor.RegisterMessage[BackUpFeedback]("nav2_msgs/action/BackUp_Feedback",
		"RIHS01_859f0344e74b313985d5c7338fc9462fcce637f25ea97500355b39201dc5c8a1")
	conductor.RegisterMessage[BackUpGoal]("nav2_msgs/action/BackUp_Goal",
		"RIHS01_07be8f5f294103a66436fbd9072f6595359431e03221039da9a8e56c2d88d8d8")
	conductor.RegisterMessage[BackUpResult]("nav2_msgs/action/BackUp_Result",
		"RIHS01_5e66d3db3244f382ecb7be337d2f28135ad7a0e66429948520a2315d97fb3acd")
	conductor.RegisterMessage[NavigateToPoseFeedback]("nav2_msgs/action/NavigateToPose_Feedback",
		"RIHS01_f37016a810a4d5541cadeb74dfc5892b1cf197e84dea241276c1de178d90420b")
	conductor.RegisterMessage[NavigateToPoseGoal]("nav2_msgs/action/NavigateToPose_Goal",
		"RIHS01_22a9dffbd6733011220460bd52edbc7843c8fc86282d40bc7ad3ca176a9dec10")
	conductor.RegisterMessage[NavigateToPoseResult]("nav2_msgs/action/NavigateToPose_Result",
		"RIHS01_ddbff7fc6d1e51d774d5defdb8398a57cb23fa8709355002d676408bb4860b85")
	conductor.RegisterMessage[SpinFeedback]("nav2_msgs/action/Spin_Feedback",
		"RIHS01_3973d0eb96c7340ba3a815ca1a623225178a882b603e0c59451ef5a5f55fee02")
	conductor.RegisterMessage[SpinGoal]("nav2_msgs/action/Spin_Goal",
		"RIHS01_f6e33f6a4d5d9c4e34cfa68f31818cd096d4251c162738ea5c01a9a8854779fc")
	conductor.RegisterMessage[SpinResult]("nav2_msgs/action/Spin_Result",
		"RIHS01_7e028af50815284a59ab43101abfd16f349963c4f0a832c33f497bfcab114a6b")
	conductor.RegisterMessage[ManageLifecycleNodesRequest]("nav2_msgs/srv/ManageLifecycleNodes_Request",
		"RIHS01_927841759575a5565b3d879a58fd035a5a69e9fdf3365c02b33cc9ad03a7a227")
	conductor.RegisterMessage[ManageLifecycleNodesResponse]("nav2_msgs/srv/ManageLifecycleNodes_Response",
		"RIHS01_3ab0ddcbe7307ad89c089d1a8749030929efc63c22ec506faf11440ec2f5c159")
	conductor.RegisterMessage[BatteryState]("sensor_msgs/msg/BatteryState",
		"RIHS01_4bee5dfce981c98faa6828b868307a0a73f992ed0789f374ee96c8f840e69741")
	conductor.RegisterMessage[Header]("std_msgs/msg/Header",
		"RIHS01_f49fb3ae2cf070f793645ff749683ac6b06203e41c891e17701b1cb597ce6a01")
	conductor.RegisterService[ManageLifecycleNodesRequest, ManageLifecycleNodesResponse]("nav2_msgs/srv/ManageLifecycleNodes",
		"RIHS01_1850f4f677251bb8f7744e3c0a87ef4f66c205e2f8740a8330251af7d1804460")
	conductor.RegisterAction[BackUpGoal, BackUpFeedback, BackUpResult](conductor.ActionInfo{
		Name:            "nav2_msgs/action/BackUp",
		SendGoal:        conductor.MessageInfo{Name: "nav2_msgs/action/BackUp_SendGoal", Hash: "RIHS01_00de8fde2e0080b4307e349b2c7ceb327dc5c914779c80ccd2949419e690b892"},
		GetResult:       conductor.MessageInfo{Name: "nav2_msgs/action/BackUp_GetResult", Hash: "RIHS01_3522c919bdbbffa283f13484f610981688138de7308e88de94a57c47c466d342"},
		FeedbackMessage: conductor.MessageInfo{Name: "nav2_msgs/action/BackUp_FeedbackMessage", Hash: "RIHS01_f279f363e5f9f485dfca4704643e12354bb5bb092dc27b0ae3dca718cff715f7"},
	})
	conductor.RegisterAction[NavigateToPoseGoal, NavigateToPoseFeedback, NavigateToPoseResult](conductor.ActionInfo{
		Name:            "nav2_msgs/action/NavigateToPose",
		SendGoal:        conductor.MessageInfo{Name: "nav2_msgs/action/NavigateToPose_SendGoal", Hash: "RIHS01_a4fcb3bee1bf32e21a0e541a943b221aa0826996e2c98f079b47022b256f48b5"},
		GetResult:       conductor.MessageInfo{Name: "nav2_msgs/action/NavigateToPose_GetResult", Hash: "RIHS01_c407920357d566771e8882b4ef4d1f1a84ee922d609920ccd57faa6d6e391dc5"},
		FeedbackMessage: conductor.MessageInfo{Name: "nav2_msgs/action/NavigateToPose_FeedbackMessage", Hash: "RIHS01_2c1b4ec1a0e3a53c9aa326aabe717670eeef0ff3d4c3351ff940613b2011728a"},
	})
	conductor.RegisterAction[SpinGoal, SpinFeedback, SpinResult](conductor.ActionInfo{
		Name:            "nav2_msgs/action/Spin",
		SendGoal:        conductor.MessageInfo{Name: "nav2_msgs/action/Spin_SendGoal", Hash: "RIHS01_63ad359dc095261afa24687d27726c47541752ba406dc5515aca94c83c4a51b8"},
		GetResult:       conductor.MessageInfo{Name: "nav2_msgs/action/Spin_GetResult", Hash: "RIHS01_7f67d68c99609b11fce83d1912c5f69b3c2e78629da43f6c74f4e02b00b49653"},
		FeedbackMessage: conductor.MessageInfo{Name: "nav2_msgs/action/Spin_FeedbackMessage", Hash: "RIHS01_65172773a4a518f36640b41d18d588319e665e7ba04a29237e7f92ba275e8388"},
	})
}
