// Code generated by conductor msggen from patrol_msgs/msg/PatrolStatus. DO NOT EDIT.

package main

import (
	"time"

	conductor "conductor.dev/conductor"
)

const (
	PatrolStatus_MODE_PATROLLING = 0
	PatrolStatus_MODE_ESTOPPED   = 1
)

//ros:type patrol_msgs/msg/PatrolStatus
type PatrolStatus struct {
	Header   Header
	Mode     uint8
	CmdStale bool
}

//ros:type std_msgs/msg/Header
type Header struct {
	Stamp   time.Time
	FrameId string
}

func init() {
	conductor.RegisterMessage[PatrolStatus]("patrol_msgs/msg/PatrolStatus",
		"RIHS01_f463fca81397d1a0aed0aa33247875ee38f6a313467496a1f1d294e007af2572")
	conductor.RegisterMessage[Header]("std_msgs/msg/Header",
		"RIHS01_f49fb3ae2cf070f793645ff749683ac6b06203e41c891e17701b1cb597ce6a01")
}
