// Code generated by conductor msggen from example_interfaces/action/Fibonacci. DO NOT EDIT.

package main

import (
	conductor "conductor.dev/conductor"
)

//ros:type example_interfaces/action/Fibonacci_Feedback
type FibonacciFeedback struct {
	Sequence []int32
}

//ros:type example_interfaces/action/Fibonacci_Goal
type FibonacciGoal struct {
	Order int32
}

//ros:type example_interfaces/action/Fibonacci_Result
type FibonacciResult struct {
	Sequence []int32
}

func init() {
	conductor.RegisterMessage[FibonacciFeedback]("example_interfaces/action/Fibonacci_Feedback",
		"RIHS01_2b12e37361da6f408d4c85bc24a18de64333f29082f2ca34b5ee33dc4c8b42a9")
	conductor.RegisterMessage[FibonacciGoal]("example_interfaces/action/Fibonacci_Goal",
		"RIHS01_226cb437e4355dcd3e914f930382a3b0cc1da81545bd319ed554e95a03255f51")
	conductor.RegisterMessage[FibonacciResult]("example_interfaces/action/Fibonacci_Result",
		"RIHS01_fea81394f25aa4502217953f1a021fb750e79c10bbd43f13dd94632da6569649")
	conductor.RegisterAction[FibonacciGoal, FibonacciFeedback, FibonacciResult](conductor.ActionInfo{
		Name:            "example_interfaces/action/Fibonacci",
		SendGoal:        conductor.MessageInfo{Name: "example_interfaces/action/Fibonacci_SendGoal", Hash: "RIHS01_d1a57fb2a4afe8c21e34fb10db206f16ce6729b28531141472df92277c55b557"},
		GetResult:       conductor.MessageInfo{Name: "example_interfaces/action/Fibonacci_GetResult", Hash: "RIHS01_1b0de0d5d29dc955d92f546706568428632771db13ec84c15ec1c1a59f424a57"},
		FeedbackMessage: conductor.MessageInfo{Name: "example_interfaces/action/Fibonacci_FeedbackMessage", Hash: "RIHS01_c1de71afd52e49a89c53d8262366884185bc0a02f78ce051c4e46b0a7fe59bb2"},
	})
}
