// Code generated by conductor msggen from moveit_msgs/action/MoveGroup. DO NOT EDIT.

package main

import (
	"time"

	conductor "conductor.dev/conductor"
)

//ros:type geometry_msgs/msg/Accel
type Accel struct {
	Linear  Vector3
	Angular Vector3
}

//ros:type geometry_msgs/msg/Point
type Point struct {
	X float64
	Y float64
	Z float64
}

//ros:type geometry_msgs/msg/Point32
type Point32 struct {
	X float32
	Y float32
	Z float32
}

//ros:type geometry_msgs/msg/Polygon
type Polygon struct {
	Points []Point32
}

//ros:type geometry_msgs/msg/Pose
type Pose struct {
	Position    Point
	Orientation Quaternion
}

//ros:type geometry_msgs/msg/PoseStamped
type PoseStamped struct {
	Header Header
	Pose   Pose
}

//ros:type geometry_msgs/msg/Quaternion
type Quaternion struct {
	X float64
	Y float64
	Z float64
	W float64
}

//ros:type geometry_msgs/msg/Transform
type Transform struct {
	Translation Vector3
	Rotation    Quaternion
}

//ros:type geometry_msgs/msg/TransformStamped
type TransformStamped struct {
	Header       Header
	ChildFrameId string
	Transform    Transform
}

//ros:type geometry_msgs/msg/Twist
type Twist struct {
	Linear  Vector3
	Angular Vector3
}

//ros:type geometry_msgs/msg/Vector3
type Vector3 struct {
	X float64
	Y float64
	Z float64
}

//ros:type geometry_msgs/msg/Wrench
type Wrench struct {
	Force  Vector3
	Torque Vector3
}

//ros:type moveit_msgs/action/MoveGroup_Feedback
type MoveGroupFeedback struct {
	State string
}

//ros:type moveit_msgs/action/MoveGroup_Goal
type MoveGroupGoal struct {
	Request         MotionPlanRequest
	PlanningOptions PlanningOptions
}

//ros:type moveit_msgs/action/MoveGroup_Result
type MoveGroupResult struct {
	ErrorCode          MoveItErrorCodes
	TrajectoryStart    RobotState
	PlannedTrajectory  RobotTrajectory
	ExecutedTrajectory RobotTrajectory
	PlanningTime       float64
}

//ros:type moveit_msgs/msg/AllowedCollisionEntry
type AllowedCollisionEntry struct {
	Enabled []bool
}

//ros:type moveit_msgs/msg/AllowedCollisionMatrix
type AllowedCollisionMatrix struct {
	EntryNames         []string
	EntryValues        []AllowedCollisionEntry
	DefaultEntryNames  []string
	DefaultEntryValues []bool
}

//ros:type moveit_msgs/msg/AttachedCollisionObject
type AttachedCollisionObject struct {
	LinkName      string
	Object        CollisionObject
	TouchLinks    []string
	DetachPosture JointTrajectory
	Weight        float64
}

//ros:type moveit_msgs/msg/BoundingVolume
type BoundingVolume struct {
	Primitives     []SolidPrimitive
	PrimitivePoses []Pose
	Meshes         []Mesh
	MeshPoses      []Pose
}

//ros:type moveit_msgs/msg/CartesianPoint
type CartesianPoint struct {
	Pose         Pose
	Velocity     Twist
	Acceleration Accel
}

//ros:type moveit_msgs/msg/CartesianTrajectory
type CartesianTrajectory struct {
	Header       Header
	TrackedFrame string
	Points       []CartesianTrajectoryPoint
}

//ros:type moveit_msgs/msg/CartesianTrajectoryPoint
type CartesianTrajectoryPoint struct {
	Point         CartesianPoint
	TimeFromStart time.Duration
}

const (
	CollisionObject_ADD    = 0
	CollisionObject_REMOVE = 1
	CollisionObject_APPEND = 2
	CollisionObject_MOVE   = 3
)

//ros:type moveit_msgs/msg/CollisionObject
type CollisionObject struct {
	Header         Header
	Pose           Pose
	Id             string
	Type           ObjectType
	Primitives     []SolidPrimitive
	PrimitivePoses []Pose
	Meshes         []Mesh
	MeshPoses      []Pose
	Planes         []Plane
	PlanePoses     []Pose
	SubframeNames  []string
	SubframePoses  []Pose
	Operation      uint8
}

//ros:type moveit_msgs/msg/Constraints
type Constraints struct {
	Name                   string
	JointConstraints       []JointConstraint
	PositionConstraints    []PositionConstraint
	OrientationConstraints []OrientationConstraint
	VisibilityConstraints  []VisibilityConstraint
}

//ros:type moveit_msgs/msg/GenericTrajectory
type GenericTrajectory struct {
	Header              Header
	JointTrajectory     []JointTrajectory
	CartesianTrajectory []CartesianTrajectory
}

//ros:type moveit_msgs/msg/JointConstraint
type JointConstraint struct {
	JointName      string
	Position       float64
	ToleranceAbove float64
	ToleranceBelow float64
	Weight         float64
}

//ros:type moveit_msgs/msg/LinkPadding
type LinkPadding struct {
	LinkName string
	Padding  float64
}

//ros:type moveit_msgs/msg/LinkScale
type LinkScale struct {
	LinkName string
	Scale    float64
}

//ros:type moveit_msgs/msg/MotionPlanRequest
type MotionPlanRequest struct {
	WorkspaceParameters          WorkspaceParameters
	StartState                   RobotState
	GoalConstraints              []Constraints
	PathConstraints              Constraints
	TrajectoryConstraints        TrajectoryConstraints
	ReferenceTrajectories        []GenericTrajectory
	PipelineId                   string
	PlannerId                    string
	GroupName                    string
	NumPlanningAttempts          int32
	AllowedPlanningTime          float64
	MaxVelocityScalingFactor     float64
	MaxAccelerationScalingFactor float64
	CartesianSpeedLimitedLink    string
	MaxCartesianSpeed            float64
	SmoothnessLevel              float64
}

const (
	MoveItErrorCodes_SUCCESS                                       = 1
	MoveItErrorCodes_UNDEFINED                                     = 0
	MoveItErrorCodes_FAILURE                                       = 99999
	MoveItErrorCodes_PLANNING_FAILED                               = -1
	MoveItErrorCodes_INVALID_MOTION_PLAN                           = -2
	MoveItErrorCodes_MOTION_PLAN_INVALIDATED_BY_ENVIRONMENT_CHANGE = -3
	MoveItErrorCodes_CONTROL_FAILED                                = -4
	MoveItErrorCodes_UNABLE_TO_AQUIRE_SENSOR_DATA                  = -5
	MoveItErrorCodes_TIMED_OUT                                     = -6
	MoveItErrorCodes_PREEMPTED                                     = -7
	MoveItErrorCodes_START_STATE_IN_COLLISION                      = -10
	MoveItErrorCodes_START_STATE_VIOLATES_PATH_CONSTRAINTS         = -11
	MoveItErrorCodes_START_STATE_INVALID                           = -26
	MoveItErrorCodes_GOAL_IN_COLLISION                             = -12
	MoveItErrorCodes_GOAL_VIOLATES_PATH_CONSTRAINTS                = -13
	MoveItErrorCodes_GOAL_CONSTRAINTS_VIOLATED                     = -14
	MoveItErrorCodes_GOAL_STATE_INVALID                            = -27
	MoveItErrorCodes_UNRECOGNIZED_GOAL_TYPE                        = -28
	MoveItErrorCodes_INVALID_GROUP_NAME                            = -15
	MoveItErrorCodes_INVALID_GOAL_CONSTRAINTS                      = -16
	MoveItErrorCodes_INVALID_ROBOT_STATE                           = -17
	MoveItErrorCodes_INVALID_LINK_NAME                             = -18
	MoveItErrorCodes_INVALID_OBJECT_NAME                           = -19
	MoveItErrorCodes_FRAME_TRANSFORM_FAILURE                       = -21
	MoveItErrorCodes_COLLISION_CHECKING_UNAVAILABLE                = -22
	MoveItErrorCodes_ROBOT_STATE_STALE                             = -23
	MoveItErrorCodes_SENSOR_INFO_STALE                             = -24
	MoveItErrorCodes_COMMUNICATION_FAILURE                         = -25
	MoveItErrorCodes_CRASH                                         = -29
	MoveItErrorCodes_ABORT                                         = -30
	MoveItErrorCodes_NO_IK_SOLUTION                                = -31
)

//ros:type moveit_msgs/msg/MoveItErrorCodes
type MoveItErrorCodes struct {
	Val     int32
	Message string
	Source  string
}

//ros:type moveit_msgs/msg/ObjectColor
type ObjectColor struct {
	Id    string
	Color ColorRGBA
}

const (
	OrientationConstraint_XYZ_EULER_ANGLES = 0
	OrientationConstraint_ROTATION_VECTOR  = 1
)

//ros:type moveit_msgs/msg/OrientationConstraint
type OrientationConstraint struct {
	Header                 Header
	Orientation            Quaternion
	LinkName               string
	AbsoluteXAxisTolerance float64
	AbsoluteYAxisTolerance float64
	AbsoluteZAxisTolerance float64
	Parameterization       uint8
	Weight                 float64
}

//ros:type moveit_msgs/msg/PlanningOptions
type PlanningOptions struct {
	PlanningSceneDiff    PlanningScene
	PlanOnly             bool
	LookAround           bool
	LookAroundAttempts   int32
	MaxSafeExecutionCost float64
	Replan               bool
	ReplanAttempts       int32
	ReplanDelay          float64
}

//ros:type moveit_msgs/msg/PlanningScene
type PlanningScene struct {
	Name                   string
	RobotState             RobotState
	RobotModelName         string
	FixedFrameTransforms   []TransformStamped
	AllowedCollisionMatrix AllowedCollisionMatrix
	LinkPadding            []LinkPadding
	LinkScale              []LinkScale
	ObjectColors           []ObjectColor
	World                  PlanningSceneWorld
	IsDiff                 bool
}

//ros:type moveit_msgs/msg/PlanningSceneWorld
type PlanningSceneWorld struct {
	CollisionObjects []CollisionObject
	Octomap          OctomapWithPose
}

//ros:type moveit_msgs/msg/PositionConstraint
type PositionConstraint struct {
	Header            Header
	LinkName          string
	TargetPointOffset Vector3
	ConstraintRegion  BoundingVolume
	Weight            float64
}

//ros:type moveit_msgs/msg/RobotState
type RobotState struct {
	JointState               JointState
	MultiDofJointState       MultiDOFJointState
	AttachedCollisionObjects []AttachedCollisionObject
	IsDiff                   bool
}

//ros:type moveit_msgs/msg/RobotTrajectory
type RobotTrajectory struct {
	JointTrajectory         JointTrajectory
	MultiDofJointTrajectory MultiDOFJointTrajectory
}

//ros:type moveit_msgs/msg/TrajectoryConstraints
type TrajectoryConstraints struct {
	Constraints []Constraints
}

const (
	VisibilityConstraint_SENSOR_Z = 0
	VisibilityConstraint_SENSOR_Y = 1
	VisibilityConstraint_SENSOR_X = 2
)

//ros:type moveit_msgs/msg/VisibilityConstraint
type VisibilityConstraint struct {
	TargetRadius        float64
	TargetPose          PoseStamped
	ConeSides           int32
	SensorPose          PoseStamped
	MaxViewAngle        float64
	MaxRangeAngle       float64
	SensorViewDirection uint8
	Weight              float64
}

//ros:type moveit_msgs/msg/WorkspaceParameters
type WorkspaceParameters struct {
	Header    Header
	MinCorner Vector3
	MaxCorner Vector3
}

//ros:type object_recognition_msgs/msg/ObjectType
type ObjectType struct {
	Key string
	Db  string
}

//ros:type octomap_msgs/msg/Octomap
type Octomap struct {
	Header     Header
	Binary     bool
	Id         string
	Resolution float64
	Data       []int8
}

//ros:type octomap_msgs/msg/OctomapWithPose
type OctomapWithPose struct {
	Header  Header
	Origin  Pose
	Octomap Octomap
}

//ros:type sensor_msgs/msg/JointState
type JointState struct {
	Header   Header
	Name     []string
	Position []float64
	Velocity []float64
	Effort   []float64
}

//ros:type sensor_msgs/msg/MultiDOFJointState
type MultiDOFJointState struct {
	Header     Header
	JointNames []string
	Transforms []Transform
	Twist      []Twist
	Wrench     []Wrench
}

//ros:type shape_msgs/msg/Mesh
type Mesh struct {
	Triangles []MeshTriangle
	Vertices  []Point
}

//ros:type shape_msgs/msg/MeshTriangle
type MeshTriangle struct {
	VertexIndices [3]uint32
}

//ros:type shape_msgs/msg/Plane
type Plane struct {
	Coef [4]float64
}

const (
	SolidPrimitive_BOX             = 1
	SolidPrimitive_SPHERE          = 2
	SolidPrimitive_CYLINDER        = 3
	SolidPrimitive_CONE            = 4
	SolidPrimitive_PRISM           = 5
	SolidPrimitive_BOX_X           = 0
	SolidPrimitive_BOX_Y           = 1
	SolidPrimitive_BOX_Z           = 2
	SolidPrimitive_SPHERE_RADIUS   = 0
	SolidPrimitive_CYLINDER_HEIGHT = 0
	SolidPrimitive_CYLINDER_RADIUS = 1
	SolidPrimitive_CONE_HEIGHT     = 0
	SolidPrimitive_CONE_RADIUS     = 1
	SolidPrimitive_PRISM_HEIGHT    = 0
)

//ros:type shape_msgs/msg/SolidPrimitive
type SolidPrimitive struct {
	Type       uint8
	Dimensions []float64
	Polygon    Polygon
}

//ros:type std_msgs/msg/ColorRGBA
type ColorRGBA struct {
	R float32
	G float32
	B float32
	A float32
}

//ros:type std_msgs/msg/Header
type Header struct {
	Stamp   time.Time
	FrameId string
}

//ros:type trajectory_msgs/msg/JointTrajectory
type JointTrajectory struct {
	Header     Header
	JointNames []string
	Points     []JointTrajectoryPoint
}

//ros:type trajectory_msgs/msg/JointTrajectoryPoint
type JointTrajectoryPoint struct {
	Positions     []float64
	Velocities    []float64
	Accelerations []float64
	Effort        []float64
	TimeFromStart time.Duration
}

//ros:type trajectory_msgs/msg/MultiDOFJointTrajectory
type MultiDOFJointTrajectory struct {
	Header     Header
	JointNames []string
	Points     []MultiDOFJointTrajectoryPoint
}

//ros:type trajectory_msgs/msg/MultiDOFJointTrajectoryPoint
type MultiDOFJointTrajectoryPoint struct {
	Transforms    []Transform
	Velocities    []Twist
	Accelerations []Twist
	TimeFromStart time.Duration
}

func init() {
	conductor.RegisterMessage[Accel]("geometry_msgs/msg/Accel",
		"RIHS01_dc448243ded9b1fcbcca24aba0c22f013dae06c354ba2d849571c0a2a3f57ca0")
	conductor.RegisterMessage[Point]("geometry_msgs/msg/Point",
		"RIHS01_6963084842a9b04494d6b2941d11444708d892da2f4b09843b9c43f42a7f6881")
	conductor.RegisterMessage[Point32]("geometry_msgs/msg/Point32",
		"RIHS01_2fc4db7cae16a4582c79a56b66173a8d48d52c7dc520ddc55a0d4bcf2a4bfdbc")
	conductor.RegisterMessage[Polygon]("geometry_msgs/msg/Polygon",
		"RIHS01_3782f9f0bf044964d692d6c017d705e37611afb1f0bf6a9dee248a7dda0f784a")
	conductor.RegisterMessage[Pose]("geometry_msgs/msg/Pose",
		"RIHS01_d501954e9476cea2996984e812054b68026ae0bfae789d9a10b23daf35cc90fa")
	conductor.RegisterMessage[PoseStamped]("geometry_msgs/msg/PoseStamped",
		"RIHS01_10f3786d7d40fd2b54367835614bff85d4ad3b5dab62bf8bca0cc232d73b4cd8")
	conductor.RegisterMessage[Quaternion]("geometry_msgs/msg/Quaternion",
		"RIHS01_8a765f66778c8ff7c8ab94afcc590a2ed5325a1d9a076ffff38fbce36f458684")
	conductor.RegisterMessage[Transform]("geometry_msgs/msg/Transform",
		"RIHS01_beb83fbe698636351461f6f35d1abb20010c43d55374d81bd041f1ba2581fddc")
	conductor.RegisterMessage[TransformStamped]("geometry_msgs/msg/TransformStamped",
		"RIHS01_0a241f87d04668d94099cbb5ba11691d5ad32c2f29682e4eb5653424bd275206")
	conductor.RegisterMessage[Twist]("geometry_msgs/msg/Twist",
		"RIHS01_9c45bf16fe0983d80e3cfe750d6835843d265a9a6c46bd2e609fcddde6fb8d2a")
	conductor.RegisterMessage[Vector3]("geometry_msgs/msg/Vector3",
		"RIHS01_cc12fe83e4c02719f1ce8070bfd14aecd40f75a96696a67a2a1f37f7dbb0765d")
	conductor.RegisterMessage[Wrench]("geometry_msgs/msg/Wrench",
		"RIHS01_018e8519d57c16adbe97c9fe1460ef21fec7e31bc541de3d653a35895677ce52")
	conductor.RegisterMessage[MoveGroupFeedback]("moveit_msgs/action/MoveGroup_Feedback",
		"RIHS01_d0cb5a6d2213e97858a73830b26b1c8f1d8989b6b47c489886527a419452fafe")
	conductor.RegisterMessage[MoveGroupGoal]("moveit_msgs/action/MoveGroup_Goal",
		"RIHS01_3e6f85f75c3bc7617dd01256f6d9b936e8c8d9965cbcfb41ff109a53e2bc3633")
	conductor.RegisterMessage[MoveGroupResult]("moveit_msgs/action/MoveGroup_Result",
		"RIHS01_188b11f0cf9d62360f554ae9a3f55cb9162767be782a7e05ee6a66371f262ebe")
	conductor.RegisterMessage[AllowedCollisionEntry]("moveit_msgs/msg/AllowedCollisionEntry",
		"RIHS01_eeb7cc3f1bfdb8c778aa7454ae90037c2749dab3ca0abdfe3dad2ae8723977db")
	conductor.RegisterMessage[AllowedCollisionMatrix]("moveit_msgs/msg/AllowedCollisionMatrix",
		"RIHS01_ac0159eec0d99f73158c7349c9d1c01b3dc7f749d75a2ea22e74a2a1091a9b05")
	conductor.RegisterMessage[AttachedCollisionObject]("moveit_msgs/msg/AttachedCollisionObject",
		"RIHS01_7fdfe7951a33a857f20fc42c9ed410a38d06dd0c209ac774ecea746dc487dc41")
	conductor.RegisterMessage[BoundingVolume]("moveit_msgs/msg/BoundingVolume",
		"RIHS01_00bb0df2edac637497dedf1778d8f217187c8d9d10f41dcfccc4d8578123ef13")
	conductor.RegisterMessage[CartesianPoint]("moveit_msgs/msg/CartesianPoint",
		"RIHS01_bbb5a879e7dd5b8443c3ce8cf374c3f314522a5540b1b4104a7b470fcc6ca907")
	conductor.RegisterMessage[CartesianTrajectory]("moveit_msgs/msg/CartesianTrajectory",
		"RIHS01_30452179003246bb9264a44854a4b720c882f63638da8da0a9afed4f565c748d")
	conductor.RegisterMessage[CartesianTrajectoryPoint]("moveit_msgs/msg/CartesianTrajectoryPoint",
		"RIHS01_63b1d2ef10058a5da0931e4de777a10fdfed3972ab166c60632f4a182b7fd5ea")
	conductor.RegisterMessage[CollisionObject]("moveit_msgs/msg/CollisionObject",
		"RIHS01_74b0acd6d56be032bf4f764b2c2633f50588b5fb2bd71e97206c59052747cf7e")
	conductor.RegisterMessage[Constraints]("moveit_msgs/msg/Constraints",
		"RIHS01_71718200459ae8fecdc4f2c9631215f7eba5ff686c701a32e231ba8b11b3592b")
	conductor.RegisterMessage[GenericTrajectory]("moveit_msgs/msg/GenericTrajectory",
		"RIHS01_b38b4942aba82576ec047a9278c47785022ce66ca86d91827aba06cdc97793c6")
	conductor.RegisterMessage[JointConstraint]("moveit_msgs/msg/JointConstraint",
		"RIHS01_4996641a8e12f5b7fde07f1cec1490324e1c4035ac5fc989ce99c9600c31e30d")
	conductor.RegisterMessage[LinkPadding]("moveit_msgs/msg/LinkPadding",
		"RIHS01_864762d9e19f758b0385427f75691374cae830495727c96405f2bad0eb20c766")
	conductor.RegisterMessage[LinkScale]("moveit_msgs/msg/LinkScale",
		"RIHS01_4666a0685f26365ccf4c9bfed0b14c654604fa0564be65c221d8d54fdc7a0f83")
	conductor.RegisterMessage[MotionPlanRequest]("moveit_msgs/msg/MotionPlanRequest",
		"RIHS01_af341d1ccabbd5f0303a6b8605cf5fb3422792c7641cc5b6e80b2d5b8458f324")
	conductor.RegisterMessage[MoveItErrorCodes]("moveit_msgs/msg/MoveItErrorCodes",
		"RIHS01_dcda8a9950cf6dd6ac221c2c0d2509f52f136afa0403dd19beacdf07e83e4a07")
	conductor.RegisterMessage[ObjectColor]("moveit_msgs/msg/ObjectColor",
		"RIHS01_4f937f7b22942a9c4a6409c20255aaad1b5d9a003ae3c0edb779698be443c127")
	conductor.RegisterMessage[OrientationConstraint]("moveit_msgs/msg/OrientationConstraint",
		"RIHS01_7a1917ac47886eb1fc170317952198b203bb797f07270475a7bbaf692cad2871")
	conductor.RegisterMessage[PlanningOptions]("moveit_msgs/msg/PlanningOptions",
		"RIHS01_2570a8ed681162d1d3afbce3a8e7ff2b6fd519676d13cf952e0a388072b255db")
	conductor.RegisterMessage[PlanningScene]("moveit_msgs/msg/PlanningScene",
		"RIHS01_0f58540ad5eab4b9ea827d53b763c793d8cabd202b3b301fcee25afa4ce1bd80")
	conductor.RegisterMessage[PlanningSceneWorld]("moveit_msgs/msg/PlanningSceneWorld",
		"RIHS01_e08e6a4a81ca6b6a6953ac758dadc2c949555093efea6a9a22d9accf62c2c099")
	conductor.RegisterMessage[PositionConstraint]("moveit_msgs/msg/PositionConstraint",
		"RIHS01_3758504dabfe337a1a660b29917e3405e5e858fdd6e9976edba04275396523df")
	conductor.RegisterMessage[RobotState]("moveit_msgs/msg/RobotState",
		"RIHS01_7c516dc15713e545cb2836c5ca745fbdcfcc10de4855a41c83e6b4bf1afc3f83")
	conductor.RegisterMessage[RobotTrajectory]("moveit_msgs/msg/RobotTrajectory",
		"RIHS01_af1dc87fb94d13e5f233e9c210d2662fa06143a8b3c6aec47c57ad45074fcce8")
	conductor.RegisterMessage[TrajectoryConstraints]("moveit_msgs/msg/TrajectoryConstraints",
		"RIHS01_4975a7925aa917c5af450713fcb8bdbc19c666d0c336a5f27056733bf8fc65f8")
	conductor.RegisterMessage[VisibilityConstraint]("moveit_msgs/msg/VisibilityConstraint",
		"RIHS01_2b479935307de421623221520ee5d9ffab494af7f4b1945114fc7e4831856c75")
	conductor.RegisterMessage[WorkspaceParameters]("moveit_msgs/msg/WorkspaceParameters",
		"RIHS01_5001636b05e9fef44faf0220f88552cab9954e55dd3ab51075f448e9aa59186e")
	conductor.RegisterMessage[ObjectType]("object_recognition_msgs/msg/ObjectType",
		"RIHS01_5eb3ee3976403366d7c50d7dbee8bec96b3bced1e752674a7194a35841632134")
	conductor.RegisterMessage[Octomap]("octomap_msgs/msg/Octomap",
		"RIHS01_9891a19a05b70ec20aa8f45db3f8300b9ab80afff32c61c549d25087da9625b0")
	conductor.RegisterMessage[OctomapWithPose]("octomap_msgs/msg/OctomapWithPose",
		"RIHS01_e65f8760aa96a2acef86b6d206175cfc78420082b6159dd3fa6ebf93f5f81979")
	conductor.RegisterMessage[JointState]("sensor_msgs/msg/JointState",
		"RIHS01_a13ee3a330e346c9d87b5aa18d24e11690752bd33a0350f11c5882bc9179260e")
	conductor.RegisterMessage[MultiDOFJointState]("sensor_msgs/msg/MultiDOFJointState",
		"RIHS01_4d4ded702cfba7ff3ec783835c1a1425f75e53939a430ff355d1fee4b3bbc40b")
	conductor.RegisterMessage[Mesh]("shape_msgs/msg/Mesh",
		"RIHS01_f2150b82d8ee7e8bc3f396a2b158aefb4b9a5510a474be271ba1268aebb55289")
	conductor.RegisterMessage[MeshTriangle]("shape_msgs/msg/MeshTriangle",
		"RIHS01_618e5c073eeb729e433ef6226e72c01d995c459fb7d76348c9700409a5020bd0")
	conductor.RegisterMessage[Plane]("shape_msgs/msg/Plane",
		"RIHS01_dfbfe8314689c850615d4a727af017e9aa86c10e369a606c8c851ef8f16c58c8")
	conductor.RegisterMessage[SolidPrimitive]("shape_msgs/msg/SolidPrimitive",
		"RIHS01_2802a15190aadc3f496584df4b0b4c5824d8a0b31aaef839faa75bc34dda38ac")
	conductor.RegisterMessage[ColorRGBA]("std_msgs/msg/ColorRGBA",
		"RIHS01_77a7a5b9ae477306097665106e0413ba74440245b1f3d0c6d6405fe5c7813fe8")
	conductor.RegisterMessage[Header]("std_msgs/msg/Header",
		"RIHS01_f49fb3ae2cf070f793645ff749683ac6b06203e41c891e17701b1cb597ce6a01")
	conductor.RegisterMessage[JointTrajectory]("trajectory_msgs/msg/JointTrajectory",
		"RIHS01_179b33eba59d676f6d967ac71fe35e7ca2f64b2f3928f4a018cec115e213796e")
	conductor.RegisterMessage[JointTrajectoryPoint]("trajectory_msgs/msg/JointTrajectoryPoint",
		"RIHS01_de8907036d8bd45aac6f30cc9044a3d4a329c42cbf719aff7d95a584cfa532d7")
	conductor.RegisterMessage[MultiDOFJointTrajectory]("trajectory_msgs/msg/MultiDOFJointTrajectory",
		"RIHS01_3a18fd095292a65cfde8833c72985a30af981f3ec44494655c6267262b443a4a")
	conductor.RegisterMessage[MultiDOFJointTrajectoryPoint]("trajectory_msgs/msg/MultiDOFJointTrajectoryPoint",
		"RIHS01_6ada1085b5ee64eaa069b074968e69f0e27c8c5e6f5bb0586dd1c834ef0e32b8")
	conductor.RegisterAction[MoveGroupGoal, MoveGroupFeedback, MoveGroupResult](conductor.ActionInfo{
		Name:            "moveit_msgs/action/MoveGroup",
		SendGoal:        conductor.MessageInfo{Name: "moveit_msgs/action/MoveGroup_SendGoal", Hash: "RIHS01_e153a193f297fef004a7d6409f782f48d46ce1223587279ee531ee5874c77611"},
		GetResult:       conductor.MessageInfo{Name: "moveit_msgs/action/MoveGroup_GetResult", Hash: "RIHS01_730c808018e9f6d10ae073e3a7e9da365e791fe5a461c6fe269af927437969fa"},
		FeedbackMessage: conductor.MessageInfo{Name: "moveit_msgs/action/MoveGroup_FeedbackMessage", Hash: "RIHS01_c5b66e44e3b976db5536bf3eb773d83238c1d1d8c53ccaa7ccba28fad55fa352"},
	})
}
